convay/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :user
  resources :invitations
  resources :clients

  resources :companies do
    get :users
  end
  resources :conversations

  resources :conversations do
    resources :messages
  end
  resources :ctransactions do
    resources :cactions
    resources :documents
  end

  get 'welcome/index'
  root 'welcome#index'

end

convay/app/controllers/ctransactions_controller.rb
class CtransactionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_ctransaction, except: [:index, :create, :new]
  before_action :authenticate_owner!, except: [:index, :new, :create]

  layout 'base_panel', :only => :index

	def index
		@ctransactions = current_user.ctransactions.select{|item| item.staus == 'progressing' and item.invitation.status == 'accepted' if item.invitation}
	  @users= User.all

  end

	def show

	end

	def new
		@ctransaction = Ctransaction.new
	end

	def edit

	end

	def create

	end

  def update
    @update_success = @ctransaction.update(ctransaction_params)
  end

	def destroy
    @delete_success = @ctransaction.delete_transaction
	end

	def add_caction
		@cactions = Caction.all
	end

	def bind_caction
		@caction = Caction.find(params[:caction_id])
		@ctransaction.cactions << @caction
		@ctransaction.save
		redirect_to company_ctransaction_path(@company, @ctransaction)
	end

	private

		def set_ctransaction
			@ctransaction = Ctransaction.find params[:id]
		end

		def authenticate_owner!
			unless @ctransaction.user == current_user
				redirect_to welcome_index_path
			end
		end

		def ctransaction_params
			params.require(:ctransaction).permit(:name, :shared_with_user_name, :role, invitation_attributes:[:property,:id]).except(:shared_with_user_name)
    end
end

convay/app/helpers/ctransactions_helper.rb
module CtransactionsHelper
end

convay/app/views/ctransactions/_transaction_detail_form.erb
<%= form_for @ctransaction ,:html => {:class => 'form-horizontal style-form'} do |f| %>
    <ul>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>Transaction</a>
          <div class="col-sm-6">
            <%= @ctransaction.name %>
          </div>
        </div>
      </li>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>Shared With</a>
          <div class="col-sm-6">
            <%= @ctransaction.shared_with_user_name %>
          </div>
        </div>
      </li>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>Vender/Buyer</a>
          <div class="col-sm-6">
            <%= @ctransaction.role %>
          </div>
        </div>
      </li>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>Property</a>
          <div class="col-sm-6">
            <%= @ctransaction.property %>
          </div>
        </div>
      </li>
    </ul>
<% end %>

convay/app/views/ctransactions/_transaction_edit_form.erb
<%= form_for @ctransaction ,:html => {:class => 'form-horizontal style-form', :id => 'modal-form'} do |f| %>
    <%= f.hidden_field :id%>
    <ul>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Transaction</a>
          <div class="col-sm-6">
            <%= @ctransaction.name %>
          </div>
        </div>
      </li>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Shared With</a>
          <div class="col-sm-6">
            <%= @ctransaction.shared_with_user_name %>
          </div>
        </div>
      </li>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Vender/Buyer</a>
          <div class="col-sm-6">
            <%= f.select :role, options_for_select([ "Sender", "Buyer" ], [@ctransaction.role]), {}, {:class => 'form-control'} %>
          </div>
        </div>
      </li>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Property</a>
          <div class="col-sm-6">
            <%= f.fields_for :invitation do |field_property| %>
                <%= field_property.text_field :property, :class => "form-control"%>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
<% end %>

convay/app/views/ctransactions/_transaction_table_row.erb
<tr id="trasaction-row-<%= @ctransaction.id %>">
  <td style="width: 20%;">
    <%= link_to edit_ctransaction_path @ctransaction.id do %>
        <%=@ctransaction.name%>
    <%end%>
  </td>
  <td style="width: 20%;"><%= @ctransaction.shared_with.email %></td>
  <td>
    <div class="progress progress-striped active">
      <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 5%">
        <span class="sr-only">45% Complete</span>
      </div>
    </div>
  </td>
  <td style="width: 15%;">
    <div class="btn-group">
      <button type="button" class="btn btn-theme0<%= @ctransaction.id % 5 %> dropdown-toggle" data-toggle="dropdown">
        Action <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to 'Edit', edit_ctransaction_path(@ctransaction.id), :remote => true %>
        </li>
        <li>
          <%= link_to 'Detail', ctransaction_path(@ctransaction.id), :remote => true %>
        </li>
        <li>
          <%= link_to "Destroy", ctransaction_path(@ctransaction.id), :remote => true, :method => :delete, :data => {:confirm => "Are you sure?"}, :class => 'delete-transaction-link' %>
        </li>
        <li>
          <%= link_to "Actions", ctransaction_cactions_path(@ctransaction.id), :remote => false %>
        </li>
        <li>
          <%= link_to "Documents", ctransaction_documents_path(@ctransaction.id) %>
        </li>
      </ul>
    </div>
  </td>
</tr>

convay/app/views/ctransactions/add_caction.html.erb
<table>
	<th></th>
	<th></th>
	<th></th>
	<% @cactions.each do |caction| %>
		<tr>
			<td>
				<%= caction.id %>
			</td>
			<td>
				<%= caction.action_name %>
			</td>
			<td>
				<%= button_to "Add", company_ctransaction_bind_caction_path(@company, @ctransaction, caction), method: :put, class: 'btn btn-default' %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to 'Back', company_ctransaction_path(@company, @ctransaction), class: 'btn btn-default' %>

convay/app/views/ctransactions/destroy.js.erb
<% if @delete_success %>
$("#trasaction-row-<%= @ctransaction.id %>").remove();
helper.showNotification("Delete Successfully", "You have deleted the client named ");
<% else %>
helper.showNotification("Delete Failed", "You have failed to delete the client named ");
<% end %>

convay/app/views/ctransactions/edit.js.erb
$(".modal-footer").show();
$(".modal-title").text("Edit a Transaction");
$("#transaction-modal").modal("show");
$("#transaction-modal").find(".modal-body").html("<%= j render 'transaction_edit_form', layout: false %>");
$("#submit-transaction-button").attr("operation","edit");

convay/app/views/ctransactions/index.html.erb
<div class="content-panel table-header01">
  <h4>Transaction List</h4>
</div>
<div class="table-responsive">
  <div class="pn white-panel position-relative">
    <div id="blog-bg">
    </div>
  <table id="transaction-table" class="table table-advance table-hover">
    <thead>
    <tr>
      <td><i class="fa fa-comment"></i>&nbsp;Transaction Name</td>
      <td><i class="fa fa-phone"></i>&nbsp;Shared With</td>
      <td><i class=" fa fa-map-marker"></i>&nbsp;Action</td>
      <td><i class=" fa fa-map-marker"></i>&nbsp;Progress</td>
    </tr>
    </thead>
    <tbody>
    <% @ctransactions.each do |ctransaction| %>
        <tr id="trasaction-row-<%= ctransaction.id %>">
          <td style="width: 20%;">
            <%= link_to edit_ctransaction_path ctransaction.id do %>
                <%=ctransaction.name%>
            <%end%>
          </td>
          <td style="width: 20%;"><%= ctransaction.shared_with.email %></td>
          <td>
            <div class="progress progress-striped active">
              <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: <%= ctransaction.progressing %>">
                <span class="sr-only">45% Complete</span>
              </div>
            </div>
            <% if ctransaction.check_shared %>
            <div class="progress progress-striped active">
              <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: <%= ctransaction.shared_progressing %>">
                <span class="sr-only">45% Complete</span>
              </div>
            </div>
            <% end %>
          </td>
          <td style="width: 15%;">
            <div class="btn-group">
              <button type="button" class="btn btn-theme0<%= ctransaction.id % 5 %> dropdown-toggle" data-toggle="dropdown">
                Action <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to 'Edit', edit_ctransaction_path(ctransaction.id), :remote => true %>
                </li>
                <li>
                  <%= link_to 'Detail', ctransaction_path(ctransaction.id), :remote => true %>
                </li>
                <li>
                  <%= link_to "Destroy", ctransaction_path(ctransaction.id), :remote => true, :method => :delete, :data => {:confirm => "Are you sure?"}, :class => 'delete-transaction-link' %>
                </li>
                <li>
                  <%= link_to "Actions", ctransaction_cactions_path(ctransaction.id), :remote => false %>
                </li>
                <li>
                  <%= link_to "Documents", ctransaction_documents_path(ctransaction.id) %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
    </div>
</div>

<!-- Modal for Deleting a Transaction  -->
<!-- Modal -->
<div id="transaction-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header create-modal-header">
        <button id="close-transaction-modal" type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Delete Transaction</h4>
      </div>
      <div id="transaction-confirm" class="modal-body">
          Are you sure to delete the chosen transaction. It can't be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-theme01" data-dismiss="modal">Close</button>
        <a id="submit-transaction-button" class="btn btn-primary" operation="">Submit</a>
      </div>
    </div>

  </div>
</div>


<script>

    var ready = function () {

        /**
         * When the send message link on our home page is clicked
         * send an ajax request to our rails app with the sender_id and
         * recipient_id
         */

        $('.start-conversation').click(function (e) {
            e.preventDefault();

            var sender_id = $(this).data('sid');
            var recipient_id = $(this).data('rip');
            var datum =  { sender_id: sender_id, recipient_id: recipient_id };
            datum = helper.appendCSRF(datum);
            $.post("/conversations", datum, function (data) {
                chatBox.chatWith(data.conversation_id);
            });
        });

        /**
         * Used to minimize the chatbox
         */

        $(document).on('click', '.toggleChatBox', function (e) {
            e.preventDefault();

            var id = $(this).data('cid');
            chatBox.toggleChatBoxGrowth(id);
        });

        /**
         * Used to close the chatbox
         */

        $(document).on('click', '.closeChat', function (e) {
            e.preventDefault();

            var id = $(this).data('cid');
            chatBox.close(id);
        });


        /**
         * Listen on keypress' in our chat textarea and call the
         * chatInputKey in chat.js for inspection
         */

        $(document).on('keydown', '.chatboxtextarea', function (event) {

            var id = $(this).data('cid');
            chatBox.checkInputKey(event, $(this), id);
        });

        /**
         * When a conversation link is clicked show up the respective
         * conversation chatbox
         */

        $('a.conversation').click(function (e) {
            e.preventDefault();

            var conversation_id = $(this).data('cid');
            chatBox.chatWith(conversation_id);
        });


    }

    $(document).ready(ready);
    $(document).on("page:load", ready);

</script>

convay/app/views/ctransactions/new.html.erb
<%= form_for @ctransaction, url: company_ctransactions_path do |f| %>
	<p>
		<%= f.label :buyer_id %><br>
		<%= f.text_field :buyer_id %>
	</p>
	<p>
		<%= f.label :vendor_id %><br>
		<%= f.text_field :vendor_id %><br>
	</p>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

convay/app/views/ctransactions/show.js.erb
$(".modal-footer").hide();
$(".modal-title").text("Edit a Transaction");
$("#transaction-modal").modal("show");
$("#transaction-modal").find(".modal-body").html("<%= j render 'transaction_detail_form', layout: false %>");
$("#submit-transaction-button").attr("operation","edit");

convay/app/views/ctransactions/update.js.erb
$(".modal-footer").show();
$(".modal-title").text("Update a Transaction");
<% if @update_success %>
$("#transaction-modal").modal("hide");
$("#trasaction-row-<%= @ctransaction.id %>").replaceWith("<%= j render 'transaction_table_row', layout: false %>");
helper.showNotification("Update Successfully", "You have updated the client named ");
<% else %>
console.log("f");
<% end %>