convay/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :user
  resources :invitations
  resources :clients

  resources :companies do
    get :users
  end
  resources :conversations

  resources :conversations do
    resources :messages
  end
  resources :ctransactions do
    resources :cactions
    resources :documents
  end

  get 'welcome/index'
  root 'welcome#index'

end

convay/app/controllers/cactions_controller.rb
class CactionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_ctransaction
  before_action :authenticate_owner!, except: [:index, :new, :create]

  layout 'base_panel', :only => :index

  def index
		@cactions = @ctransaction.cactions
    @temp_new_caction = Caction.new
    @shared_actions = @ctransaction.shared_with_transaction.cactions if @ctransaction.shared_with_transaction
	end

	def show
		
	end

	def new
		@caction = Caction.new
	end

	def edit
    @caction = Caction.find params[:id]
	end

	def create
    @caction = Caction.new(caction_params)
    @caction.save
	end

	def update
    @caction = Caction.find params[:id]
    @update_success = @caction.update caction_params
	end

	def destroy
    @caction = Caction.find params[:id]
    @destroy_success = @caction.destroy
	end

	private
		def set_ctransaction
      @ctransaction = Ctransaction.find params[:ctransaction_id]
		end

		def caction_params
			params.require(:caction).permit(:action_name, :id, :state, :ctransaction_id)
		end

    def authenticate_owner!
      unless @ctransaction.user == current_user
        redirect_to welcome_index_path
      end
    end

end

convay/app/helpers/cactions_helper.rb
module CactionsHelper
end

convay/app/views/cactions/_action_detail_form.erb
<%= form_for @caction, url: ctransaction_cactions_path ,:html => {:class => 'form-horizontal style-form', :id => 'modal-form'} do |f| %>
    <%= f.hidden_field :id%>
    <%= f.hidden_field :ctransaction_id, :value => @ctransaction.id %>
    <ul>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Task Name</a>
          <div class="col-sm-6">
           <p>
            <%= @caction.action_name %>
           </p>
          </div>
        </div>
      </li>

      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Status</a>
          <div class="col-sm-6">
            <p>
              <%= @caction.state %>
            </p>
          </div>
        </div>
      </li>

    </ul>

<% end %>

convay/app/views/cactions/_action_edit_form.erb
<%= form_for @caction, url: ctransaction_cactions_path ,:html => {:class => 'form-horizontal style-form', :id => 'modal-form'} do |f| %>
    <%= f.hidden_field :id%>
    <%= f.hidden_field :ctransaction_id, :value => @ctransaction.id %>
    <ul>
      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Task Name</a>
          <div class="col-sm-6">
            <%= f.text_field :action_name, :class=> "form-control" %>
            <p id="action_name_edit_error" class="client-form-error">
              <%= @caction.errors[:action_name].first %>
            </p>
          </div>
        </div>
      </li>

      <li>
        <div class="form-group">
          <a class="col-sm-3 col-sm-3 control-label"><i class="fa fa-phone"></i>&nbsp;Status</a>
          <div class="col-sm-6">
            <%= f.select :state, options_for_select([ ["Processing",1], ["Done",0] ], :selected => @caction.state), {}, {:class => 'form-control'} %>
          </div>
        </div>
      </li>

    </ul>

<% end %>

convay/app/views/cactions/_action_table_row.erb
<li id="action-row-<%= @caction.id%>" style="position: relative; left: 0px; top: 0px;" class="list-primary">
  <div class="task-title">
    <span class="task-title-sp"><%= @caction.action_name %></span>
    <% if @caction.state == 0 %>
        <span class="badge bg-theme">Done</span>
    <% end %>

    <% if @caction.state == 1 %>
        <span class="badge bg-success">Processing</span>
    <% end %>
    <div class="pull-right hidden-phone">
      <%= link_to edit_ctransaction_caction_path(@ctransaction.id, @caction.id), :remote => true, :class => "btn btn-primary btn-xs fa fa-pencil" do %>
      <% end %>
      <%= link_to ctransaction_caction_path(@ctransaction.id, @caction.id), :remote => true, :class => "btn btn-success btn-xs fa fa-check" do %>
      <% end %>
      <%= link_to ctransaction_caction_path(@ctransaction.id, @caction.id), :remote => true, :method => :delete, :data => {:confirm => "Are you sure?"}, :class => 'btn btn-danger btn-xs fa fa-trash-o' do %>
      <% end %>
    </div>
  </div>
</li>
<br>

convay/app/views/cactions/_new_action_form.erb
<%= form_for @temp_new_caction, :url => "" do |f| %>
    <p>
      <%= f.label :action_name, :class => "form-font-style"%>*<br>
      <%= f.text_field :action_name, :class => "form-control" %>
    <p>
    <p id="action_name__error" class="action-form-error"></p>
      <strong>Note:</strong> The first name of your client.
      Letters and underscores only. Must start with a capital
      letter and be less than 32 characters.
    <%= token_tag(nil) %>

<% end %>

convay/app/views/cactions/create.js.erb
$(".modal-footer").show();
$(".modal-title").text("Create a New Task");
<% if @caction.valid? %>
$("#action-modal").modal("hide");
$("ul.mylist").append("<%= j render 'action_table_row', layout: false %>");
helper.showNotification("Create Successfully", "You have created a new client: ");
<% else %>
$("#action-modal").find(".modal-body").html("");
$("#action-modal").find(".modal-body").html("<%= j render 'action_edit_form', layout: false %>");
$("#submit-action-button").attr("operation","new");
<% end %>

convay/app/views/cactions/destroy.js.erb
<% if @destroy_success %>
$("#action-row-<%= @caction.id %>").remove();
helper.showNotification("Delete Successfully", "You have deleted the client named ");
<% else %>
helper.showNotification("Delete Failed", "You have failed to delete the client named ");
<% end %>

convay/app/views/cactions/edit.js.erb
$(".modal-footer").show();
$(".modal-title").text("Edit a Task");
$("#action-modal").modal("show");
$("#action-modal").find(".modal-body").html("<%= j render 'action_edit_form', layout: false %>");
$("#submit-action-button").attr("operation","edit");

convay/app/views/cactions/index.html.erb
<div class="content-panel table-header01">
  <h4>Transaction List</h4>
</div>
<div class="pn white-panel position-relative" style="text-align: left;">
<div class="col-md-12">
  <section class="task-panel tasks-widget">
    <div class="panel-body">
      <div class="task-content">
        <ul id="sortable" class="mylist task-list">
          <% @cactions.each do |action| %>
          <li id="action-row-<%= action.id%>" style="position: relative; left: 0px; top: 0px;" class="list-primary">
            <div class="task-title">
              <span class="task-title-sp"><%= action.action_name %></span>&nbsp;
              <% if action.state == 0 %>
              <span class="badge bg-theme">Done</span>
              <% end %>

              <% if action.state == 1 %>
                  <span class="badge bg-success">Processing</span>
              <% end %>
              <div class="pull-right hidden-phone">
                <%= link_to edit_ctransaction_caction_path(@ctransaction.id, action.id), :remote => true, :class => "btn btn-primary btn-xs fa fa-pencil" do %>
                <% end %>
                <%= link_to ctransaction_caction_path(@ctransaction.id, action.id), :remote => true, :class => "btn btn-success btn-xs fa fa-check" do %>
                <% end %>
                <%= link_to ctransaction_caction_path(@ctransaction.id, action.id), :remote => true, :method => :delete, :data => {:confirm => "Are you sure?"}, :class => 'btn btn-danger btn-xs fa fa-trash-o' do %>
                <% end %>
              </div>
            </div>
          </li>
          <br>
          <% end %>
        </ul>
      </div>
      <div class=" add-task-row">
        <%= link_to new_ctransaction_caction_path, :remote => true, :class => 'btn btn-success btn-sm pull-left' do %>
            Add a new Task
        <% end %>
      </div>
    </div>
  </section>
</div><!--/col-md-12 -->

</div>


<br>
<br>
<br>

<li id="hidden-action-row" style="position: relative; left: 0px; top: 0px;" class="list-primary">
  <div class="task-title">
    <span class="task-title-sp"></span>
    <span class="badge bg-theme"></span>
    <div class="pull-right hidden-phone" style="display: none;">
      <a attribute="done" class="btn btn-success btn-xs fa fa-check edit-action-button"  data-toggle="modal" href="#edit-action-modal"></a>
      <a class="btn btn-danger btn-xs fa fa-trash-o delete-action-button"  data-toggle="modal" href="#delete-action-modal"></a>
      <a attribute="processing" class="btn btn-primary btn-xs fa fa-pencil edit-action-button"  data-toggle="modal" href="#edit-action-modal"></a>
    </div>
  </div>
</li>



<div class="content-panel table-header01">
  <h4>Shared List</h4>
</div>
<div class="pn white-panel position-relative" style="text-align: left;">
  <div class="col-md-12">
    <section class="task-panel tasks-widget">

      <div class="panel-body">
        <div class="task-content">
          <ul id="sortable" class="task-list ui-sortable">
            <% if @shared_actions %>
            <% @shared_actions.each do |action| %>
                <li id="action-row-<%= action.id%>" style="position: relative; left: 0px; top: 0px;" class="list-primary">
                  <div class="task-title">
                    <span class="task-title-sp"><%= action.action_name %></span>
                    <% if action.state == 0 %>
                        <span class="badge bg-theme">Done</span>
                    <% end %>

                    <% if action.state == 1 %>
                        <span class="badge bg-success">Processing</span>
                    <% end %>
                  </div>
                </li>
            <% end %>
            <% end %>
          </ul>
        </div>

      </div>
    </section>
  </div><!--/col-md-12 -->
</div>



<!-- Modal for creating a action  -->
<!-- Modal -->
<div id="create-action-modal" class="modal fade" role="dialog">
  <div class="modal-dialog create-client-form">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button id="close-create-action-modal" type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Action Info</h4>
      </div>
      <div class="modal-body">
        <%= render 'new_action_form' %>
        <div class="modal-footer">
          Fields * are required.
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <a id="create-action-button" class="btn btn-theme01">Submit</a>
        </div>
      </div>
    </div>

  </div>
</div>


<!-- Modal for Deleting a action  -->
<!-- Modal -->
<div id="delete-action-modal" class="modal fade" role="dialog">
  <div class="modal-dialog create-client-form">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header delete-modal-header">
        <button id="close-delete-action-modal" type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Delete Action</h4>
      </div>
      <div id="delete-action-confirm" class="modal-body">
          Are you sure to delete the chosen action? It can't be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a id="delete-action-button" class="btn btn-theme01">Submit</a>
      </div>
    </div>

  </div>
</div>
<!-- Modal ends -->

<!-- Modal for Editing a action  -->
<!-- Modal -->
<div id="edit-action-modal" class="modal fade" role="dialog">
  <div class="modal-dialog create-client-form">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header delete-modal-header">
        <button id="close-delete-action-modal" type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Action</h4>
      </div>
      <div id="edit-action-confirm" class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a id="edit-action-button" class="btn btn-theme01">Submit</a>
      </div>
    </div>

  </div>
</div>
<!-- Modal ends -->


<!-- Modal for a Action  -->
<!-- Modal -->
<div id="action-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button id="close-modal" type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a id="submit-action-button" class="btn btn-theme01" operation="">Submit</a>
      </div>
    </div>

  </div>
</div>



<script>
    jQuery(document).ready(function() {
        TaskList.initTaskWidget();
    });

    $(function() {
        $( "#sortable" ).sortable();
        $( "#sortable" ).disableSelection();
    });

</script>

<script src="/assets/panel/tasks.js" type="text/javascript"></script>

convay/app/views/cactions/new.js.erb
$(".modal-footer").show();
$(".modal-title").text("Create a New Task");
$("#action-modal").modal("show");
$("#action-modal").find(".modal-body").html("<%= j render 'action_edit_form', layout: false %>");
$("#submit-action-button").attr("operation","new");

convay/app/views/cactions/show.js.erb
$(".modal-title").text("Task Detail");
$(".modal-footer").hide();
$("#action-modal").modal("show");
$("#action-modal").find(".modal-body").html("<%= j render 'action_detail_form', layout: false %>");

convay/app/views/cactions/update.js.erb
$(".modal-footer").show();
$(".modal-title").text("Update a Client");
<% if @update_success %>
$("#action-modal").modal("hide");
$("#action-row-<%= @caction.id %>").replaceWith("<%= j render 'action_table_row', layout: false %>");
helper.showNotification("Update Successfully", "You have updated the client named ");
<% else %>
$("#action-modal").find(".modal-body").html("");
$("#action-modal").find(".modal-body").html("<%= j render 'action_edit_form', layout: false %>");
$("#submit-action-button").attr("operation","edit");
<% end %>