convay/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :user
  resources :invitations
  resources :clients

  resources :companies do
    get :users
  end
  resources :conversations

  resources :conversations do
    resources :messages
  end
  resources :ctransactions do
    resources :cactions
    resources :documents
  end

  get 'welcome/index'
  root 'welcome#index'

end

convay/app/views/shared/_navigation.html.erb
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Convay</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="">
              <i class="glyphicon glyphicon-user"></i> <%= current_user.email %> <span class=" caret"></span></a>
            <ul id="g-account-menu" class="dropdown-menu" role="menu">
              <li><a href="">My Profile</a></li>
              <li>
              	<%= link_to destroy_user_session_path, method: :delete do %>
              		<i class="glyphicon glyphicon-lock"></i> Logout
              	<% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <div>
          	<%= link_to 'Log in', new_user_session_path, class: "navbar-text" %>
			<%= link_to 'Sign up', new_user_registration_path, class: "navbar-text" %>
          </div>
        <% end %>
      </ul>
    </div>
  </div><!-- /container -->
</div>

convay/app/views/shared/_sidebar.html.erb
<a href=""><strong><i class="glyphicon glyphicon-wrench"></i> Tools</strong></a>
<hr>
<ul class="nav nav-stacked">
    <li class="nav-header"> <a href="" data-toggle="collapse" data-target="#cactionMenu" data-remote="true">Actions <i class="glyphicon glyphicon-chevron-right"></i></a>
        <ul class="nav nav-stacked collapse" id="cactionMenu">
            <li>
                <%= link_to company_cactions_path(current_user.company) do %>
                    <i class="glyphicon glyphicon-list"></i> All
                <% end %>
            </li>
            <li>
                <%= link_to new_company_caction_path(current_user.company) do %>
                    <i class="glyphicon glyphicon-list"></i> New
                <% end %>

            </li>
        </ul>
    </li>
    <li class="nav-header"> <a href="" data-toggle="collapse" data-target="#clientMenu" data-remote="true">Clients <i class="glyphicon glyphicon-chevron-right"></i></a>
        <ul class="nav nav-stacked collapse" id="clientMenu">
            <li>
                <%= link_to clients_path do %>
                    <i class="glyphicon glyphicon-list"></i> All
                <% end %>
            </li>
            <li>
                <%= link_to new_client_path do %>
                    <i class="glyphicon glyphicon-list"></i> New
                <% end %>

            </li>
        </ul>
    </li>
    <li class="nav-header"> <a href="" data-toggle="collapse" data-target="#companyMenu" data-remote="true">Companies <i class="glyphicon glyphicon-chevron-right"></i></a>
        <ul class="nav nav-stacked collapse" id="companyMenu">
            <li>
                <%= link_to companies_path do %>
                    <i class="glyphicon glyphicon-list"></i> All
                <% end %>
            </li>
            <li>
                <%= link_to new_company_path do %>
                    <i class="glyphicon glyphicon-list"></i> New
                <% end %>

            </li>
        </ul>
    </li>
    <li class="nav-header"> <a href="" data-toggle="collapse" data-target="#ctransactionMenu" data-remote="true">Transactions <i class="glyphicon glyphicon-chevron-right"></i></a>
        <ul class="nav nav-stacked collapse" id="ctransactionMenu">
            <li>
                <%= link_to company_ctransactions_path(current_user.company) do %>
                    <i class="glyphicon glyphicon-list"></i> All
                <% end %>
            </li>
            <li>
                <%= link_to new_company_ctransaction_path(current_user.company) do %>
                    <i class="glyphicon glyphicon-list"></i> New
                <% end %>

            </li>
        </ul>
    </li>
</ul>

convay/app/views/shared/_titlebar.html.erb
<ul class="list-inline pull-right">
    <li><a href="#"><i class="glyphicon glyphicon-cog"></i></a></li>
    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-comment"></i><span class="count">3</span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">1. Is there a way..</a></li>
            <li><a href="#">2. Hello, admin. I would..</a></li>
            <li><a href="#"><strong>All messages</strong></a></li>
        </ul>
    </li>
    <li><a href="#"><i class="glyphicon glyphicon-user"></i></a></li>
    <li><a title="Add Widget" data-toggle="modal" href="#addWidgetModal"><span class="glyphicon glyphicon-plus-sign"></span> Add Widget</a></li>
</ul>
<a href="#"><strong><i class="glyphicon glyphicon-dashboard"></i> My Dashboard</strong></a>
<hr>